//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int id { get; set; }
        public string name { get; set; }
        public string dob { get; set; }
        public string desi { get; set; }
        public string qua { get; set; }
        public string sex { get; set; }
        public string cntid { get; set; }
        public string email { get; set; }
        public string isrelo { get; set; }
        public string mob { get; set; }
        public string img { get; set; }
    }
}
